### ISSUE TITLE
The image strategy puts binary data in the session

### ISSUE THREAD

**Issue by jesper-friis** [EMMC-ASBL/oteapi-core#107]
The image strategy must not place binary data into the session.

Any binary (non-json serialisable and UTF-8 encodable) data placed in the session will make the services fail, due to
"oteapi-services/app/routers/session.py", line 124, in _update_session()
```python
    await redis.set(session_id, session.json().encode("utf-8"))
```

This might be considered a bug in oteapi-services. A workaround is to use the datacache, which is more accepting (supports e.g. the buffer protocol) although it also uses json as serialiser.

**Comment by CasperWA** [comment]
Should we support binary data in `oteapi-services`?
