### ISSUE TITLE
Problems accessing configurations' fields

### ISSUE THREAD

**Issue by xAlessandroC** [EMMC-ASBL/oteapi-core#113]
### Brief explanation of the problem
I have errors in accessing the configuration fields of a strategy: the main error I encounter is **XXX object has no attribute YYY**.

### Environment setup
1. Have a running OntoKB + OntoREC docker container. The relative docker-compose file can be found [here](https://gitlab.cc-asp.fraunhofer.de/ontotrans/ontotranscorecomponents/-/blob/master/docker-compose.yml)
2. Have a running oteapi-service docker container.
    - repo version: https://github.com/EMMC-ASBL/oteapi-services/commit/f71498a4638a9ecf2fec8b216f20cd26585b8390
    - add the following line to requirements.txt in order to install the ontokb-plugin:
    oteapi-ontokb-plugin @ git+https://github.com/xAlessandroC/oteapi-ontokb-plugin@89ce60bdc2eae85d99abebec5ec3ad4a40edf85b
    - put **full_ontology_inferred_remapped.rdf** file in the project and add this line to the Dockerfile:
    COPY full_ontology_inferred_remapped.rdf ./
3. Have otelib installed

### Steps to reproduce the error (1)
1. Create OTEClient
```
client = OTEClient('http://localhost:<YOUR OTEAPI PORT>')
```
2. Create an otelib dataresource filter
```
uploader = client.create_dataresource(
        accessUrl = "http://host.docker.internal:<YOUR ONTOREC PORT>",
        accessService = "datasource/ontokb_upload",
        configuration = {
            "database":"temp",
            "filename":"full_ontology_inferred_remapped.rdf",
            "fileConfig": {
                "downloadUrl":"file:///full_ontology_inferred_remapped.rdf",
                "mediaType":"application/json",
                "configuration":{
                    "text" : True,
                    "encoding" : "utf-8"
                }
            }
        }
    )
```
3. Create pipeline and get the result
```
totalpipe = uploader
totalpipe.get()
```

In the oteapi-service docker container log I get the error
```
File "/usr/local/lib/python3.9/site-packages/oteapi_ontokb_plugin/strategies/ontokb_upload.py", line 82, in get
    cache = DataCache(self.resource_config.configuration.datacache_config)
AttributeError: 'AttrDict' object has no attribute 'datacache_config'
```

### Steps to reproduce the error (2)
1. Same of the previous case
2. Add **"datacache_config" : None** to ontokb_upload strategy configuration
```
uploader = client.create_dataresource(
        accessUrl = "http://host.docker.internal:<YOUR ONTOREC PORT>",
        accessService = "datasource/ontokb_upload",
        configuration = {
            "database":"temp",
            "filename":"full_ontology_inferred_remapped.rdf",
            "fileConfig": {
                "downloadUrl":"file:///full_ontology_inferred_remapped.rdf",
                "mediaType":"application/json",
                "configuration":{
                    "text" : True,
                    "encoding" : "utf-8"
                }
            },
           "datacache_config" : None
        }
    )
```

In the oteapi-service docker container log I get the error
```
File "/usr/local/lib/python3.9/site-packages/oteapi/plugins/factories.py", line 108, in _get_strategy_name
    return config.downloadUrl.scheme if config.downloadUrl is not None else ""  # type: ignore[union-attr]  # pylint: disable=line-too-long
AttributeError: 'dict' object has no attribute 'downloadUrl'
```

**Comment by xAlessandroC** [comment]
Here the file to put in the oteapi-services container:
[full_ontology_inferred_remapped.zip](https://github.com/EMMC-ASBL/oteapi-core/files/8198824/full_ontology_inferred_remapped.zip)

**Comment by CasperWA** [comment]
I think the latter issue explained here is the same as #123, which will be fixed by #124.

**Comment by CasperWA** [comment]
The first issue (step 1) seems to be an issue with the `oteapi_ontokb_plugin` repository.

**Comment by xAlessandroC** [comment]
> The first issue (step 1) seems to be an issue with the `oteapi_ontokb_plugin` package.

What kind of issue could have caused that? I defined datacache_config as an optional field of the configuration.

**Comment by CasperWA** [comment]
> > The first issue (step 1) seems to be an issue with the `oteapi_ontokb_plugin` package.
> 
> What kind of issue could have caused that? I defined datacache_config as an optional field of the configuration.

Let's take a look at that in the `oteapi_ontokb_plugin` repository instead.

**Comment by xAlessandroC** [comment]
I see. Sorry for the misunderstanding but it could be a problem in the definition of our Pydantic model or in the global settings of the plugin?
Do you prefer I open an issue on `oteapi_ontokb_plugin`?

**Comment by CasperWA** [comment]
No worries. Yeah, let's take a look at the first issue outlined here in the plugin repository :)

**Comment by CasperWA** [comment]
@xAlessandroC I have just updated `oteapi-core` to v0.1.4 and also pushed the changes through to `oteapi-services` building a new Docker image available at `ghcr.io/emmc-asbl/oteapi:latest`.
Please update everything and see if you still get the same issue :)

**Comment by xAlessandroC** [comment]
Perfect, thank you! I'll update my environment and let you know if the second error is resolved :)

I created an issue on `oteapi_ontokb_plugin` [issue #1](https://github.com/xAlessandroC/oteapi-ontokb-plugin/issues/1) repo to solve the first issue. I updated the content with some new experiment I've done. Briefly, the error pops up only with the otelib/oteapi-service framework, the plugin seems to work if I use directly oteapi-core v0.1.2.

**Comment by xAlessandroC** [comment]
I removed the full_ontology_inferred_remapped.rdf zip for privacy reasons, if you still need it please let me know and I will send it by mail

**Comment by xAlessandroC** [comment]
Hi Casper, I tried the last version of the oteapi framework (v 0.1.4) but I had some trouble to start a development image of the oteapi-services container. I created an issue on the repo [#89](https://github.com/EMMC-ASBL/oteapi-services/issues/89)
