### ISSUE TITLE
Publish docker image

### ISSUE THREAD

**Issue by francescalb** [EMMC-ASBL/oteapi-core#15]
To be used by oteapi-deploy. Should update image in oteapi-deploy at the same time.

**Comment by CasperWA** [comment]
CD tests should be added for this as well to make sure the resulting `Dockerfile` can at least be built. If possible it can be tested whether it can be run as well.

**Comment by jesper-friis** [comment]
I guess that this issue should be moved to oteapi-services

**Comment by CasperWA** [comment]
I'd say this has been "fixed" by EMMC-ASBL/oteapi-services#2.

Feel free to re-open this issue if you feel that is not the case @francescalb.
