### ISSUE TITLE
New Function strategy

### ISSUE THREAD

**Issue by jesper-friis** [EMMC-ASBL/oteapi-core#19]
In order to reduce the amount of boilerplate code that has to be maintained I will suggest that we instead of implementing two new strategies just add a new method to the existing download and parse strategies.

The parse strategies can optionally implement a `serialise()` method that uses `mediaType`/`accessService` from `ResourceConfig` to serialise content into the data cache. 

Similarly can the download strategies optionally implement a `put()` method that uses `downloadUrl`/`accessUrl` from `ResourceConfig` to read content from the cache and upload it. 

The cache is controlled with the same configurations as for downloading and parsing. The `serialisation()` method will, like the `parse()` method, instantiate the download strategy, but call the `put()` method instead.

If implemented like this, the download strategy should at registration time inform whether it implements `get()` and/or `put()`. Alternatively this could be probed automatically by the API. Similarly for the parse strategy.

**Comment by CasperWA** [comment]
I am highjacking this issue to represent the Function strategy implementation.

The conclusion concerning the "serialization" and "upload" strategies, is that serialization will be implemented in part through a new "Function" strategy, which is a synchronous equivalent of the "Transformation" strategy.
Upload will be handled through configuration of download strategies - with a suggestion that these strategy types probably should be renamed to a more encompassing name.
