### ISSUE TITLE
xlsx parse strategy fails parsing file on Windows

### ISSUE THREAD

**Issue by TorgeirUstad** [EMMC-ASBL/oteapi-core#23]
The DataCache prevents the parser from parsing the file:

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '[path to cache directory]\\oteapi-download-var0r09f.xlsx'

**Comment by CasperWA** [comment]
PR #52 adds a CI job to run `pytest` in Windows (also for both Python 3.9 and 3.10).

**Comment by jesper-friis** [comment]
@TorgeirUstad, as far as I can see should cache.getfile() close the file before yielding the filename. Are you sure that this issue hasn't been fixed?

**Comment by jesper-friis** [comment]
The last issue was fixed in PR #70. I also pushed the `read_only=False` workaround to that PR.
