### ISSUE TITLE
Ensure celery-strategy is returning correct job-id

### ISSUE THREAD

**Issue by quaat** [EMMC-ASBL/oteapi-core#236]
This issue goes beyond the oteapi-core. Ensure celery-strategy is returning correct job-id when a remote job is triggered. From the oteapi-service, ensure the status of the job can be correctly introspected. At the termination of the remote celery-worker a return value (model) is submitted back to the broker service (Redis), ensure this data can be fetched from the oteapi-services

**Comment by CasperWA** [comment]
I'll just try to summarize the OP:

- [ ] Ensure celery-strategy is returning correct job-id when a remote job is triggered.
- [ ] Ensure the status of the job can be correctly introspected from the OTEAPI Services.
- [ ] Ensure remote return value (model) data can be fetched from the OTEAPI Services.

**Comment by CasperWA** [comment]
Exactly _what_ is the "correct" job-id when a remote job is triggered? Is it the "local" Celery server's job ID or is it the job ID of a remotely running Celery server?
