### ISSUE TITLE
Importing oteapi.strategies.parse.image fails for Python 3.9

### ISSUE THREAD

**Issue by jesper-friis** [EMMC-ASBL/oteapi-core#269]
See this failing CI job for oteapi-dlite:

https://github.com/EMMC-ASBL/oteapi-dlite/actions/runs/5055736279/jobs/9072325123?pr=139

On line 47 you see that `from oteapi.strategies.parse.image import (ImageDataParseStrategy, ImageParserConfig, ImageParserResourceConfig)` fails. This happens for Python 3.9, not Python 3.10.

**Comment by CasperWA** [comment]
I've found (locally) that using `typing_extensions` fixes the issue and still allows for the usage of `Literal`.

**Comment by CasperWA** [comment]
As a comment, I also found that the oteapi-core tests were failing due to the same issue. I don't know where the regression has occurred? Perhaps in pydantic?

**Comment by CasperWA** [comment]
Fixes by #270
