### ISSUE TITLE
Tests require installation

### ISSUE THREAD

**Issue by jesper-friis** [EMMC-ASBL/oteapi-core#50]
Since the entry points are made available through installation, you have to install before the tests can find the strategies they are testing.

This should be documented.

A even better solution would be if we had a test fixture that could sniff the strategies and make them available for the tests without installation? That would especially be helpful for the plugin template.

**Comment by TorgeirUstad** [comment]
Is this related to what is done in the first commit in PR #35?

**Comment by CasperWA** [comment]
Note, there should be pytest fixtures now, with which one can load any strategy whether they are installed or not - so I consider this issue resolved.
The tests for the strategies, however, still need to be written ;)
