### ISSUE TITLE
pyproject.toml addopts line doesn't work on Windows

### ISSUE THREAD

**Issue by TorgeirUstad** [EMMC-ASBL/oteapi-core#51]
Probably because

`--cov=./oteapi/`

isn't valid on Windows.

General note: We should have workflows for Windows as well.

**Comment by CasperWA** [comment]
I have assigned myself here, but actually, you might be implementing this in your testing PR? Or?

**Comment by CasperWA** [comment]
You can just use `--cov=oteapi` instead

**Comment by TorgeirUstad** [comment]
You can do it. The testing PR is based on an older master, so I will have to make significant changes to it anyway, to make it compliant with the newest master (whatever that may be - it seemingly changes fundamentally all the time). So the fewer changes I have to make to that branch, the better.

Also, this is something that should be fixed as soon as possible, so we shouldn't wait for my PR.
