### ISSUE TITLE
Document that oteapi-core must be installed editable in order to test with pytest

### ISSUE THREAD

**Issue by jesper-friis** [EMMC-ASBL/oteapi-core#62]

**Comment by CasperWA** [comment]
I do not think this is the case anymore? But in any case - I'd consider it standard practice to have an editable install when developing - and it's mainly/only developers who will run the tests.

**Comment by CasperWA** [comment]
I recently tested this, and it does not seem to be the case any longer. Closing this issue.
If the issue resurfaces, please open a new issue.
