### ISSUE TITLE
ResourceConfig.configuration should be a dict

### ISSUE THREAD

**Issue by jesper-friis** [EMMC-ASBL/oteapi-core#65]
`ResourceConfig.configuration` cannot be a `DataCacheConfig`, since that would disallow to use it to configure other strategy implementations. It should be a dict, of the form:

```python
    configuration: Dict[str, Any] = Field(
        {},
        description="Resource-specific configuration options given as key/value-pairs.",
    )
```

See also issue #64

**Comment by CasperWA** [comment]
Disagree - as I also commented in #67: `DataCacheConfig` is a pydantic model that subclasses `AttrDict`, which re-implements `Dict`, while also allowed access to the values by calling the keys as attributes.
