### ISSUE TITLE
Remove image/eps as supported image format

### ISSUE THREAD

**Issue by TorgeirUstad** [EMMC-ASBL/oteapi-core#68]
The image parse strategy is based on the `Image` class in the `Pillow` package, which supports the `EPS (Encapsulated PostScript)` format. However, reading an `EPS` image requires that `Ghostscript` is installed on the system.

Instead of requiring `Ghostscript` to be installed, we should remove `image/eps` from the list of supported image formats.

**Comment by CasperWA** [comment]
I think the better solution here is to keep the strategy in, but only properly test it in CI. If one does not have `Ghostscript` installed locally, the test will simply be skipped.

**Comment by CasperWA** [comment]
That's a good point. We can have the strategy simply raise if it doesn't find Ghostscript available on the system? And then actually test that as well. I think that's fair.
It should then also be documented as a requirement/dependency in the system when implementing an OTE API service.
