### ISSUE TITLE
Setup documentation framework

### ISSUE THREAD

**Issue by CasperWA** [EMMC-ASBL/oteapi-core#9]

**Comment by CasperWA** [comment]
I will start setting up a similar documentation framework as has been setup for EMMOntoPy (see the public documentation [here](https://emmo-repo.github.io/EMMO-python/latest/)).

**Comment by francescalb** [comment]
> I will start setting up a similar documentation framework as has been setup for EMMOntoPy (see the public documentation [here](https://emmo-repo.github.io/EMMO-python/latest/)).

Very good, then we decided not to go for the other solution menitoned previously?

**Comment by CasperWA** [comment]
> Very good, then we decided not to go for the other solution menitoned previously?

No. There has been no final decision on this. However, since this does not require a lot of effort as it will basically be copy-pasting the solution from EMMOntoPy (more or less), while also keeping the documentation in MarkDown, easily transferrable to Sphinx if needed, then I see no need to hold back.
If we decide to switch to Sphinx this can be (easily) done, in my opinion - once a template and infrastructure is in place for it.
